server:
  port: 8080

app:
  env: ${APP_ENV:local}
  version: ${APP_VERSION:unknown}

spring:
  application:
    name: greeting-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: iso_demo, shop_demo
    default-schema: iso_demo
    create-schemas: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n'
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
