server:
  port: 8084


spring:
  config:
    activate:
      on-profile: local
  application:
    name: reactor-workshop
  r2dbc:
    url: r2dbc:postgresql://localhost:5435/reactor_workshop
    username: app
    password: app
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5435/reactor_workshop
    user: app
    password: app
    locations: classpath:db/migration
    schemas: reactor_workshop
    default-schema: reactor_workshop
    create-schemas: true
    baseline-on-migrate: true

logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n'
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql.QUERY: INFO
    com.example.reactorworkshop.config.LocalR2dbcSqlLogConfig: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
